### ISSUE TITLE
Fix navbar with dropdown

### ISSUE THREAD

**Issue by anishpawaskar** [Real-Dev-Squad/members-site#104]
## Description
1. Remove crypto link from navbar
![image](https://github.com/Real-Dev-Squad/members-site/assets/22213872/a76cd8a9-fe80-487a-b58e-d8ff038d8892)

2. Make a RDS logo clickable and when user click on it, it should redirect you to `https://www.realdevsquad.com`

https://github.com/Real-Dev-Squad/members-site/assets/22213872/3aff42d3-7d86-41a8-b3bf-1ecab3504c8f

3. Create a dropdown component. When a user logged in and click on their profile then the dropdown component should show up 
![image](https://github.com/Real-Dev-Squad/members-site/assets/22213872/73d58881-2232-41e1-b947-25c15a069389)

**Design doc:-**
https://docs.google.com/document/d/1_4VorCtwUplxhBkYE9af7uxbYrQEZBGj4xSkoZRzxAU/edit

## Task break down:-

1. Navbar fix :-
- [x] Remove crypto button
- [x] Make RDS logo clickable

2. Dropdown menu component :-
- [x] Create dropdown menu component
- [ ] Write test for `Navbar` as well as `Dropdown menu` component
